---
sidebar: sidebar 
permalink: reference-limitations-azure.html 
keywords: limitations, ha, azure, pay-as-you-go, paygo, cloud solution provider, vm, flash cache 
summary: Queste limitazioni note sono specifiche di Cloud Volumes ONTAP in Microsoft Azure. 
---
= Limitazioni note per Cloud Volumes ONTAP in Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le seguenti limitazioni note sono specifiche di Cloud Volumes ONTAP in Microsoft Azure.  Assicurati di rivedere anchelink:reference-limitations.html["Limitazioni per Cloud Volumes ONTAP in tutti i provider cloud"] .



== Limitazioni nell'utilizzo delle estensioni delle VM di Azure

Cloud Volumes ONTAP non supporta le estensioni delle macchine virtuali (VM) di Azure perché influiscono sulle operazioni di gestione BlueXP . Durante la distribuzione, BlueXP impedisce l'installazione di estensioni sulle VM. Se le estensioni sono già installate sulle VM Cloud Volumes ONTAP esistenti, contattare il supporto Microsoft Azure per rimuoverle. Per indicazioni, fare riferimento all'articolo della knowledge base (KB) https://kb.netapp.com/Cloud/Cloud_Volumes_ONTAP/Can_Azure_VM_Management_Extensions_be_installed_into_Cloud_Volume_ONTAP["È possibile installare Azure VM Management Extensions in Cloud Volume ONTAP?"^]

A partire dal 14 luglio 2025, NetApp invierà e-mail e ti notificherà in BlueXP se vengono rilevate estensioni VM sulle tue VM Cloud Volumes ONTAP .



== Limitazioni della cache Flash

Cloud Volumes ONTAP utilizza l'archiviazione NVMe locale in alcuni tipi di VM come _Flash Cache_.  Nota questa limitazione:

* Il riscaldamento della cache dopo un riavvio non è supportato.




== Limitazioni con distribuzioni ad alta disponibilità

Le coppie ad alta disponibilità (HA) non sono supportate in alcune regioni.

https://bluexp.netapp.com/cloud-volumes-global-regions["Visualizza l'elenco delle regioni di Azure supportate"^] .



== Limitazioni con le distribuzioni HA in singole zone di disponibilità

A partire da Cloud Volumes ONTAP 9.15.1, è possibile distribuire istanze di macchine virtuali (VM) in modalità HA in singole zone di disponibilità (AZ) in Azure.  Per informazioni sui criteri che supportano questa funzionalità, fare riferimento a https://docs.netapp.com/us-en/cloud-volumes-ontap-9151-relnotes/reference-new.html#deploy-ha-pairs-in-single-availability-zones-on-azure["Distribuisci coppie HA in singole zone di disponibilità in Azure"^] .

Se la versione Cloud Volumes ONTAP è precedente alla 9.15.1 o se una qualsiasi di queste condizioni non viene soddisfatta, entra in vigore il modello di distribuzione precedente che utilizza i set di disponibilità.  Questo vale solo per le configurazioni HA.
