---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, detaching, snapmanager, features, disks, aggregates, features, svm 
summary: Le limitazioni note identificano piattaforme, dispositivi o funzioni che non sono supportati da questa versione del prodotto o che non interagiscono correttamente con esso. Esamina attentamente queste limitazioni. 
---
= Limitazioni note per Cloud Volumes ONTAP in tutti i provider cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le limitazioni note identificano piattaforme, dispositivi o funzioni che non sono supportati da questa versione del prodotto o che non interagiscono correttamente con esso. Esamina attentamente queste limitazioni.

Le seguenti limitazioni si applicano a Cloud Volumes ONTAP in tutti i provider cloud: AWS, Azure e Google Cloud.



== Funzionalità ONTAP non supportate

Le seguenti funzionalità non sono supportate da Cloud Volumes ONTAP:

* Deduplicazione in linea a livello di aggregato
* Deduplicazione in background a livello aggregato
* Centro di manutenzione del disco
* Sanificazione del disco
* Specchiatura FabricPool
* Canale in fibra (FC)
* Piscine Flash
* Volumi infiniti
* Gruppi di interfaccia
* Failover LIF intranodo
* MetroCluster
* Verifica multi-amministratore
+
L'abilitazione della verifica multi-amministratore su Cloud Volumes ONTAP comporterà una configurazione non supportata.

* RAID4, RAID-DP, RAID-TEC (RAID0 è supportato)
* Processore di servizi
* Modalità SnapLock Compliance ed Enterprise (è supportato solo Cloud WORM)
* SnapMirror Sincrono
* VLAN
* Disponibilità continua (CA) per PMI
+
https://kb.netapp.com/on-prem/ontap/da/NAS/NAS-KBs/What_are_SMB_Continuous_Availability_CA_Shares["Condivisioni SMB costantemente disponibili"^] per operazioni non distruttive non sono supportate.





== Numero massimo di operazioni di replica simultanee

Il numero massimo di trasferimenti SnapMirror o SnapVault contemporanei per Cloud Volumes ONTAP è 100 per nodo, indipendentemente dal tipo di istanza o dal tipo di macchina.



== Gli snapshot del provider cloud non devono essere utilizzati per i piani di backup e ripristino

Non dovresti utilizzare gli snapshot del tuo provider cloud come parte del tuo piano di backup e ripristino per i dati Cloud Volumes ONTAP .  Per eseguire il backup e il ripristino dei dati ospitati su Cloud Volumes ONTAP , è sempre consigliabile utilizzare copie Snapshot ONTAP o soluzioni di backup di terze parti.

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-backup-to-cloud.html["Scopri come utilizzare il BlueXP backup and recovery per eseguire il backup e il ripristino dei dati ONTAP"^] .


NOTE: I punti di coerenza ONTAP nel file system WAFL determinano la coerenza dei dati.  Solo ONTAP può mettere in pausa il file system WAFL per effettuare un backup coerente con gli arresti anomali.



== Cloud Volumes ONTAP supporta solo istanze VM riservate e on-demand

Cloud Volumes ONTAP può essere eseguito su un'istanza VM riservata o su richiesta del tuo provider cloud.  Altri tipi di istanze VM non sono supportati.



== Non dovrebbero essere utilizzate soluzioni di gestione automatica delle risorse applicative

Le soluzioni di gestione automatica delle risorse applicative non devono gestire i sistemi Cloud Volumes ONTAP .  In caso contrario, la configurazione potrebbe cambiare, diventando non supportata.  Ad esempio, la soluzione potrebbe modificare Cloud Volumes ONTAP in un tipo di istanza VM non supportato.



== Gli aggiornamenti software devono essere completati da BlueXP

Gli aggiornamenti di Cloud Volumes ONTAP devono essere completati da BlueXP.  Non dovresti aggiornare Cloud Volumes ONTAP tramite System Manager o la CLI.  Ciò potrebbe compromettere la stabilità del sistema.



== La distribuzione Cloud Volumes ONTAP non deve essere modificata dalla console del tuo provider cloud

Le modifiche apportate alla configurazione di Cloud Volumes ONTAP dalla console del provider cloud determinano una configurazione non supportata.  Qualsiasi modifica alle risorse Cloud Volumes ONTAP create e gestite BlueXP può influire sulla stabilità del sistema e sulla capacità di BlueXP di gestirlo.


NOTE: Dopo la distribuzione iniziale, è supportata la modifica del nome della sottoscrizione di Azure utilizzato per le risorse Cloud Volumes ONTAP .



== I dischi e gli aggregati devono essere gestiti da BlueXP

Tutti i dischi e gli aggregati devono essere creati ed eliminati direttamente da BlueXP.  Non dovresti eseguire queste azioni da un altro strumento di gestione.  Ciò potrebbe compromettere la stabilità del sistema, ostacolare la possibilità di aggiungere dischi in futuro e potenzialmente generare commissioni ridondanti per il provider cloud.



== Limitazione della licenza SnapManager

Le licenze per server SnapManager sono supportate con Cloud Volumes ONTAP.  Le licenze per sistema di archiviazione (suite SnapManager ) non sono supportate.



== Limitazioni con agenti ed estensioni di terze parti

Gli agenti di terze parti e le estensioni VM non sono supportati sulle istanze di macchine virtuali Cloud Volumes ONTAP .
