---
sidebar: sidebar 
permalink: reference-limits-gcp.html 
keywords: limits, maximum, storage, aggregates, disks, volumes, capacity, luns, size, storage virtual machine, SVM 
summary: Cloud Volumes ONTAP ha limiti di configurazione dello storage in Google Cloud per garantire operazioni affidabili.  Per ottenere le migliori prestazioni, non configurare il sistema ai valori massimi. 
---
= Limiti di archiviazione per Cloud Volumes ONTAP in Google Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP ha limiti di configurazione dello storage per garantire operazioni affidabili.  Per ottenere le migliori prestazioni, non configurare il sistema ai valori massimi.



== Capacità massima del sistema per licenza

La capacità massima del sistema Cloud Volumes ONTAP è determinata dalla sua licenza. La capacità massima del sistema include l'archiviazione basata su disco e l'archiviazione di oggetti utilizzata per la suddivisione in livelli dei dati.

NetApp non supporta il superamento del limite di capacità del sistema. Se si raggiunge il limite di capacità concesso in licenza, BlueXP visualizza un messaggio che richiede un'azione e non consente più di aggiungere dischi aggiuntivi.

Per alcune configurazioni, i limiti del disco impediscono di raggiungere il limite di capacità utilizzando solo i dischi.  Puoi raggiungere il limite di capacità tramite https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["suddivisione in livelli dei dati inattivi nell'archiviazione degli oggetti"^] .  Per maggiori dettagli, fare riferimento ai limiti del disco riportati di seguito.

.Limite di capacità per le licenze basate sulla capacità
Grazie alle licenze basate sulla capacità, ogni sistema Cloud Volumes ONTAP supporta la suddivisione in livelli per l'archiviazione di oggetti. La capacità totale a livelli può essere scalata fino al limite del bucket del provider cloud. Sebbene la licenza non imponga restrizioni di capacità, dovresti seguire le https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["Migliori pratiche FabricPool"^] per garantire prestazioni ottimali, affidabilità ed efficienza dei costi durante la configurazione e la gestione del tiering. Fare riferimento al  https://cloud.google.com/storage/docs/buckets["Documentazione di Google Cloud"^] per maggiori informazioni.

Limiti di capacità per altri tipi di licenza::


[cols="25,75"]
|===
| Licenza | Capacità massima del sistema (dischi + archiviazione oggetti) 


| Freemium | 500 GB 


| Esplora PAYGO | 2 TB (il tiering dei dati non è supportato con Explore) 


| Standard PAYGO | 10 TB 


| PAYGO Premium | 368 TB 


| Licenza basata su nodi | 2 PiB (richiede più licenze) 
|===
.Per una coppia HA, il limite di capacità concesso in licenza è per nodo o per l'intera coppia HA?
Il limite di capacità è per l'intera coppia HA. Non è per nodo. Ad esempio, se si utilizza la licenza Premium, è possibile avere fino a 368 TB di capacità tra entrambi i nodi.

.Per una coppia HA, i dati mirror vengono conteggiati nel limite di capacità concesso in licenza?
No, non è così. I dati in una coppia HA vengono replicati in modo sincrono tra i nodi, in modo che siano disponibili in caso di errore in Google Cloud. Ad esempio, se si acquista un disco da 8 TB sul nodo A, BlueXP alloca anche un disco da 8 TB sul nodo B, che viene utilizzato per i dati in mirroring. Sebbene sia impostata una capacità di 16 TB, solo 8 TB vengono conteggiati nel limite della licenza.



== Limiti aggregati

Cloud Volumes ONTAP raggruppa i dischi di Google Cloud Platform in _aggregati_.  Gli aggregati forniscono spazio di archiviazione ai volumi.

[cols="2*"]
|===
| Parametro | Limite 


| Numero massimo di aggregati di dati ^1^  a| 
* 99 per nodo singolo
* 64 per un'intera coppia HA




| Dimensione massima dell'aggregato | 256 TB di capacità grezza ^2^ 


| Dischi per aggregato | 1-6 ^3^ 


| Numero massimo di gruppi RAID per aggregato | 1 
|===
Note:

. Il numero massimo di aggregati di dati non include l'aggregato radice.
. I dischi che compongono l'aggregato determinano il limite di capacità dell'aggregato. Questo limite non include l'archiviazione di oggetti utilizzata per la suddivisione in livelli dei dati.
. Tutti i dischi di un aggregato devono avere le stesse dimensioni.




== Limiti del disco e dei livelli

La tabella seguente mostra la capacità massima del sistema con soli dischi e con dischi e dati a freddo suddivisi in livelli per l'archiviazione di oggetti.  I limiti del disco sono specifici per i dischi che contengono dati utente.  I limiti non includono il disco di avvio, il disco di root o la NVRAM.

[cols="60,40"]
|===
| Parametro | Limite 


| Numero massimo di dischi dati  a| 
* 124 per sistemi a nodo singolo
* 123 per nodo per coppie HA




| Dimensione massima del disco | 64 TB 


| Capacità massima del sistema con soli dischi | 256 TB ^1^ 


| Capacità massima del sistema con dischi e suddivisione in livelli di dati freddi in un bucket di Google Cloud Storage | Dipende dalla licenza.  Fare riferimento ai limiti massimi di capacità del sistema sopra indicati. 
|===
^1^ Questo limite è definito dai limiti delle macchine virtuali in Google Cloud Platform.



== Limiti delle VM di archiviazione

Alcune configurazioni consentono di creare VM di archiviazione aggiuntive (SVM) per Cloud Volumes ONTAP.

Questi sono i limiti testati. La configurazione di più VM di archiviazione non è supportata.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-managing-svms-gcp.html["Scopri come creare VM di archiviazione aggiuntive"^] .

[cols="2*"]
|===
| Tipo di licenza | Limite di archiviazione VM 


| *Freemium*  a| 
24 VM di archiviazione totali ^1^



| *PAYGO o BYOL basato sulla capacità* ^2^  a| 
24 VM di archiviazione totali ^1^



| *BYOL basato su nodi* ^3^  a| 
24 VM di archiviazione totali ^1^



| *PAYGO basato su nodi*  a| 
* 1 VM di archiviazione per la fornitura di dati
* 1 VM di archiviazione per il ripristino di emergenza


|===
. Queste 24 VM di archiviazione possono gestire dati o essere configurate per il disaster recovery (DR).
. Per le licenze basate sulla capacità, non sono previsti costi di licenza aggiuntivi per le VM di storage aggiuntive, ma è previsto un addebito minimo di capacità pari a 4 TiB per VM di storage.  Ad esempio, se crei due VM di archiviazione e ciascuna ha 2 TiB di capacità fornita, ti verrà addebitato un costo totale di 8 TiB.
. Per BYOL basato su nodi, è richiesta una licenza aggiuntiva per ogni VM di storage aggiuntiva per la distribuzione dei dati oltre alla prima VM di storage fornita con Cloud Volumes ONTAP per impostazione predefinita. Contatta il team del tuo account per ottenere una licenza aggiuntiva per la macchina virtuale di archiviazione.
+
Le VM di archiviazione configurate per il disaster recovery (DR) non richiedono una licenza aggiuntiva (sono gratuite), ma vengono conteggiate nel limite delle VM di archiviazione.  Ad esempio, se si dispone di 12 VM di storage per il servizio dati e 12 VM di storage configurate per il disaster recovery, si è raggiunto il limite e non è possibile creare ulteriori VM di storage.





== Limiti di archiviazione logici

[cols="22,22,56"]
|===
| Archiviazione logica | Parametro | Limite 


.2+| *File* | Dimensione massima ^2^ | 128 TB 


| Massimo per volume | Dipende dalla dimensione del volume, fino a 2 miliardi 


| * Volumi FlexClone * | Profondità di clonazione gerarchica ^12^ | 499 


.3+| * Volumi FlexVol * | Massimo per nodo | 500 


| Dimensione minima | 20 MB 


| Dimensione massima ^3^ | 300 TiB 


| *Qtrees* | Massimo per FlexVol volume | 4.995 


| *Copie istantanee* | Massimo per FlexVol volume | 1.023 
|===
. La profondità di clonazione gerarchica è la profondità massima di una gerarchia annidata di volumi FlexClone che può essere creata da un singolo FlexVol volume.
. A partire da ONTAP 9.12.1P2, il limite è 128 TB.  In ONTAP 9.11.1 e nelle versioni precedenti, il limite è di 16 TB.
. La creazione FlexVol volume fino a una dimensione massima di 300 TiB è supportata utilizzando i seguenti strumenti e le seguenti versioni minime:
+
** System Manager e ONTAP CLI a partire da Cloud Volumes ONTAP 9.12.1 P2 e 9.13.0 P2
** BlueXP a partire da Cloud Volumes ONTAP 9.13.1






== Limiti di archiviazione iSCSI

[cols="3*"]
|===
| archiviazione iSCSI | Parametro | Limite 


.4+| *LUN* | Massimo per nodo | 1.024 


| Numero massimo di mappe LUN | 1.024 


| Dimensione massima | 16 TB 


| Massimo per volume | 512 


| *igruppi* | Massimo per nodo | 256 


.2+| *Iniziatori* | Massimo per nodo | 512 


| Massimo per igroup | 128 


| *Sessioni iSCSI* | Massimo per nodo | 1.024 


.2+| *LIF* | Massimo per porta | 1 


| Massimo per set di porte | 32 


| *Portset* | Massimo per nodo | 256 
|===


== Le coppie Cloud Volumes ONTAP HA non supportano la restituzione immediata dello storage

Dopo il riavvio di un nodo, il partner deve sincronizzare i dati prima di poter restituire l'archiviazione.  Il tempo necessario per risincronizzare i dati dipende dalla quantità di dati scritti dai client mentre il nodo era inattivo e dalla velocità di scrittura dei dati durante il periodo di restituzione.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-ha-google-cloud.html["Scopri come funziona l'archiviazione in una coppia Cloud Volumes ONTAP HA in esecuzione in Google Cloud"^] .
