---
sidebar: sidebar 
permalink: reference-limitations-aws.html 
keywords: limitations, aws, amazon web services, flashe cache, alarms, cloudwatch, giveback, govcloud, c2s, aws outpost, outposts 
summary: Queste limitazioni note sono specifiche di Cloud Volumes ONTAP in Amazon Web Services. 
---
= Limitazioni note per Cloud Volumes ONTAP in AWS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le seguenti limitazioni note sono specifiche di Cloud Volumes ONTAP in Amazon Web Services.  Assicurati di rivedere anchelink:reference-limitations.html["Limitazioni per Cloud Volumes ONTAP in tutti i provider cloud"] .



== Limitazioni di AWS Outpost

Se disponi di un AWS Outpost, puoi distribuire Cloud Volumes ONTAP in quell'Outpost selezionando l'Outpost VPC nella procedura guidata Ambiente di lavoro.  L'esperienza è la stessa di qualsiasi altra VPC residente in AWS.  Tieni presente che dovrai prima distribuire un connettore nel tuo AWS Outpost.

Ci sono alcune limitazioni da sottolineare:

* Al momento sono supportati solo i sistemi Cloud Volumes ONTAP a nodo singolo
* Le istanze EC2 che puoi utilizzare con Cloud Volumes ONTAP sono limitate a quelle disponibili nel tuo Outpost
* Al momento sono supportati solo gli SSD General Purpose (gp2)




== Limitazioni della cache Flash

I tipi di istanza C5D e R5D includono l'archiviazione NVMe locale, che Cloud Volumes ONTAP utilizza come _Flash Cache_.  Si prega di notare le seguenti limitazioni:

* Per sfruttare i miglioramenti delle prestazioni di Flash Cache fino a Cloud Volumes ONTAP 9.12.0, è necessario disabilitare la compressione su tutti i volumi.  Quando si distribuisce o si esegue l'aggiornamento a Cloud Volumes ONTAP 9.12.1, non è necessario disabilitare la compressione.
+
È possibile scegliere nessuna efficienza di archiviazione quando si crea un volume da BlueXP, oppure è possibile creare un volume e quindi http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-vsmg/GUID-8508A4CB-DB43-4D0D-97EB-859F58B29054.html["disabilitare la compressione dei dati utilizzando la CLI"^] .

* Il riscaldamento della cache dopo un riavvio non è supportato con Cloud Volumes ONTAP.




== Falsi allarmi segnalati da Amazon CloudWatch

Cloud Volumes ONTAP non rilascia CPU quando è inattivo, quindi https://aws.amazon.com/cloudwatch/["Amazon CloudWatch"^] può segnalare un avviso di CPU elevata per l'istanza EC2 perché rileva un utilizzo del 100%.  Puoi ignorare questo allarme.  Il comando statistiche ONTAP visualizza il reale utilizzo delle CPU.



== Le coppie Cloud Volumes ONTAP HA non supportano la restituzione immediata dello storage

Dopo il riavvio di un nodo, il partner deve sincronizzare i dati prima di poter restituire l'archiviazione.  Il tempo necessario per risincronizzare i dati dipende dalla quantità di dati scritti dai client mentre il nodo era inattivo e dalla velocità di scrittura dei dati durante il periodo di restituzione.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-ha.html["Scopri come funziona l'archiviazione in una coppia Cloud Volumes ONTAP HA in esecuzione su AWS"^] .
