---
sidebar: sidebar 
permalink: reference-limits-aws.html 
keywords: limits, maximum, storage, aggregates, disks, volumes, capacity, luns, size, storage virtual machine, SVM, ebs 
summary: Cloud Volumes ONTAP ha limiti di configurazione dello storage in AWS per garantire operazioni affidabili.  Per ottenere le migliori prestazioni, non configurare il sistema ai valori massimi. 
---
= Limiti di archiviazione per Cloud Volumes ONTAP in AWS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP ha limiti di configurazione dello storage per garantire operazioni affidabili.  Per ottenere le migliori prestazioni, non configurare il sistema ai valori massimi.



== Capacità massima del sistema per licenza

La capacità massima del sistema include l'archiviazione basata su disco e l'archiviazione di oggetti utilizzata per la suddivisione in livelli dei dati.

NetApp non supporta il superamento del limite di capacità del sistema. Se si raggiunge il limite di capacità concesso in licenza, BlueXP visualizza un messaggio che richiede un'azione e non consente più di aggiungere dischi aggiuntivi.

Per alcune configurazioni, i limiti del disco impediscono di raggiungere il limite di capacità utilizzando solo i dischi.  In questi casi, è possibile raggiungere il limite di capacità https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["suddivisione in livelli dei dati inattivi nell'archiviazione degli oggetti"^] .  Per maggiori dettagli, fare riferimento ai limiti di capacità e disco riportati di seguito.

.Limite di capacità per le licenze basate sulla capacità
Grazie alle licenze basate sulla capacità, ogni sistema Cloud Volumes ONTAP supporta la suddivisione in livelli per l'archiviazione di oggetti. La capacità totale a livelli può essere scalata fino al limite del bucket del provider cloud. Sebbene la licenza non imponga restrizioni di capacità, dovresti seguire le https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["Migliori pratiche FabricPool"^] per garantire prestazioni ottimali, affidabilità ed efficienza dei costi durante la configurazione e la gestione del tiering. Fare riferimento al  https://docs.aws.amazon.com/AmazonS3/latest/userguide/BucketRestrictions.html["Documentazione AWS"^] per maggiori informazioni.

Limiti di capacità per altri tipi di licenza::


[cols="25,75"]
|===
| Licenza | Capacità massima del sistema (dischi + archiviazione oggetti) 


| Freemium | 500 GB 


| Esplora PAYGO | 2 TiB (il tiering dei dati non è supportato con Explore) 


| Standard PAYGO | 10 TiB 


| PAYGO Premium | 368 TiB 


| Licenza basata su nodi | 2 PiB (richiede più licenze) 
|===
.Per HA, il limite di capacità della licenza è per nodo o per l'intera coppia HA?
Il limite di capacità è per l'intera coppia HA. Non è per nodo. Ad esempio, la licenza Premium consente fino a 368 TiB su entrambi i nodi.

.Per un sistema HA in AWS, i dati mirror vengono conteggiati nel limite di capacità?
No, non è così. I dati in una coppia AWS HA vengono replicati in modo sincrono tra i nodi, in modo che siano disponibili in caso di errore.  Ad esempio, se si acquista un disco da 8 TiB sul nodo A, BlueXP alloca anche un disco da 8 TiB sul nodo B, che viene utilizzato per i dati in mirroring.  Sebbene siano stati forniti 16 TiB di capacità, solo 8 TiB vengono conteggiati nel limite della licenza.



== Limiti aggregati

Cloud Volumes ONTAP utilizza i volumi EBS come dischi e li raggruppa in _aggregati_.  Gli aggregati forniscono spazio di archiviazione ai volumi.

[cols="2*"]
|===
| Parametro | Limite 


| Numero massimo di aggregati | Singolo nodo: uguale al limite del disco Coppie HA: 18 in un nodo ^1^ 


| Dimensione massima aggregata ^2^  a| 
* 96 TiB di capacità grezza
* 128 TiB di capacità grezza con volumi elastici ^3^




| Dischi per aggregato ^4^  a| 
* 1-6
* 1-8 con volumi elastici ^3^




| Numero massimo di gruppi RAID per aggregato | 1 
|===
Note:

. Non è possibile creare 18 aggregati su entrambi i nodi in una coppia HA perché ciò supererebbe il limite del disco dati.
. La dimensione massima aggregata dipende dai dischi e non include l'archiviazione degli oggetti utilizzata per la suddivisione in livelli dei dati.
. Se si dispone di una configurazione che supporta la funzionalità Amazon EBS Elastic Volumes, un aggregato può contenere fino a 8 dischi, che forniscono fino a 128 TiB di capacità. Per impostazione predefinita, nei sistemi Cloud Volumes ONTAP 9.11.0 e versioni successive, Amazon EBS Elastic Volumes è abilitato quando si utilizzano dischi gp3 o io1. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-aws-elastic-volumes.html["Scopri di più sul supporto per Elastic Volumes"^]
. Tutti i dischi di un aggregato devono avere le stesse dimensioni.




== Limiti di disco e livelli per istanza EC2

I limiti di capacità variano a seconda della famiglia di tipi di istanze EC2 utilizzata e se si utilizza un sistema a nodo singolo o una coppia HA.

Le seguenti note forniscono dettagli sui numeri che vedrai nelle tabelle sottostanti:

* I limiti del disco sono specifici per i dischi che contengono dati utente.
+
I limiti non includono il disco di avvio e il disco di root.

* Viene indicata la capacità massima del sistema quando si utilizzano solo dischi e quando si utilizzano dischi e livelli di dati freddi per l'archiviazione di oggetti.
* Cloud Volumes ONTAP utilizza volumi EBS come dischi, con una dimensione massima del disco di 16 TiB.




=== Limiti per le diverse modalità di distribuzione delle licenze basate sulla capacità

I seguenti limiti del disco si applicano ai sistemi Cloud Volumes ONTAP che utilizzano un pacchetto di licenze basato sulla capacità. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html["Scopri le opzioni di licenza Cloud Volumes ONTAP"^]


NOTE: Per i limiti massimi di capacità del sistema e di capacità di suddivisione in livelli dei dati per configurazioni a nodo singolo e HA, fare riferimento a<<cap-license-aws>> .



==== Nodo singolo

[cols="18,18,32,width=100%,options="]
|===


| Esempio | Numero massimo di dischi per nodo | Capacità massima del sistema con soli dischi 


| istanze c5, m5 e r5 | 21 | 336 TiB 


 a| 
* m5dn.24xlarge
* m6id.32xlarge

| 19 ^1^ | 304 TiB 
|===
. Questo tipo di istanza ha più dischi NVMe locali rispetto ad altri tipi di istanza, il che significa che è supportato un numero inferiore di dischi dati.




==== coppie HA

[cols="18,18,32,width=100%,options="]
|===


| Esempio | Numero massimo di dischi per nodo | Capacità massima del sistema con soli dischi 


| istanze c5, m5 e r5 | 18 | 288 TiB 


 a| 
* m5dn.24xlarge
* m6id.32xlarge

| 16 ^1^ | 256 TiB 
|===
. Questo tipo di istanza ha più dischi NVMe locali rispetto ad altri tipi di istanza, il che significa che è supportato un numero inferiore di dischi dati.




=== Limiti per diverse modalità di distribuzione delle licenze basate sui nodi

I seguenti limiti del disco si applicano ai sistemi Cloud Volumes ONTAP che utilizzano licenze basate sui nodi, ovvero il modello di licenza della generazione precedente che consentiva di concedere in licenza Cloud Volumes ONTAP per nodo. Le licenze basate sui nodi sono ancora disponibili per i clienti esistenti.

È possibile acquistare più licenze basate su nodi per un sistema a nodo singolo o a coppia HA Cloud Volumes ONTAP BYOL per allocare più di 368 TiB di capacità, fino al limite massimo di capacità del sistema testato e supportato di 2 PiB. Tieni presente che i limiti del disco possono impedirti di raggiungere il limite di capacità utilizzando solo i dischi. Puoi superare il limite del disco https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["suddivisione in livelli dei dati inattivi nell'archiviazione degli oggetti"^] . https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-node-licenses.html["Scopri come aggiungere licenze di sistema aggiuntive a Cloud Volumes ONTAP"^] . Sebbene Cloud Volumes ONTAP supporti fino alla capacità massima di sistema testata e supportata di 2 PiB, il superamento del limite di 2 PiB determina una configurazione di sistema non supportata.

Le regioni AWS Secret Cloud e Top Secret Cloud supportano l'acquisto di più licenze basate su nodi a partire da Cloud Volumes ONTAP 9.12.1.



==== Nodo singolo con PAYGO Premium

[cols="18,18,32,32"]
|===
| Esempio | Numero massimo di dischi per nodo | Capacità massima del sistema con soli dischi | Capacità massima del sistema con dischi e livelli di dati 


| istanze c5, m5 e r5 | 21 ^1^ | 336 TiB | 368 TiB 


 a| 
* m5dn.24xlarge
* m6id.32xlarge

| 19 ^2^ | 304 TiB | 368 TiB 
|===
. 21 dischi dati è il limite per le _nuove_ distribuzioni di Cloud Volumes ONTAP.  Se si aggiorna un sistema creato con la versione 9.7 o precedente, il sistema continuerà a supportare 22 dischi.  Nei nuovi sistemi che utilizzano questi tipi di istanza è supportato un disco dati in meno grazie all'aggiunta di un disco core a partire dalla versione 9.8.
. Questo tipo di istanza ha più dischi NVMe locali rispetto ad altri tipi di istanza, il che significa che è supportato un numero inferiore di dischi dati.




==== Nodo singolo con BYOL

[cols="18,18,16,16,16,16"]
|===
| Esempio | Numero massimo di dischi per nodo 2+| Capacità massima del sistema con una licenza 2+| Capacità massima del sistema con più licenze 


2+|  | *Solo dischi* | *Dischi + suddivisione in livelli dei dati* | *Solo dischi* | *Dischi + suddivisione in livelli dei dati* 


| istanze c5, m5 e r5 | 21 ^1^ | 336 TiB | 368 TiB | 336 TiB | 2 PiB 


 a| 
* m5dn.24xlarge
* m6id.32xlarge

| 19 ^2^ | 304 TiB | 368 TiB | 304 TiB | 2 PiB 
|===
. 21 dischi dati è il limite per le _nuove_ distribuzioni di Cloud Volumes ONTAP.  Se si aggiorna un sistema creato con la versione 9.7 o precedente, il sistema continuerà a supportare 22 dischi.  Nei nuovi sistemi che utilizzano questi tipi di istanza è supportato un disco dati in meno grazie all'aggiunta di un disco core a partire dalla versione 9.8.
. Questo tipo di istanza ha più dischi NVMe locali rispetto ad altri tipi di istanza, il che significa che è supportato un numero inferiore di dischi dati.




==== HA si abbina a PAYGO Premium

[cols="18,18,32,32"]
|===
| Esempio | Numero massimo di dischi per nodo | Capacità massima del sistema con soli dischi | Capacità massima del sistema con dischi e livelli di dati 


| istanze c5, m5 e r5 | 18 ^1^ | 288 TiB | 368 TiB 


 a| 
* m5dn.24xlarge
* m6id.32xlarge

| 16 ^2^ | 256 TiB | 368 TiB 
|===
. 18 dischi dati è il limite per le _nuove_ distribuzioni di Cloud Volumes ONTAP.  Se si aggiorna un sistema creato con la versione 9.7 o precedente, il sistema continuerà a supportare 19 dischi.  Nei nuovi sistemi che utilizzano questi tipi di istanza è supportato un disco dati in meno grazie all'aggiunta di un disco core a partire dalla versione 9.8.
. Questo tipo di istanza ha più dischi NVMe locali rispetto ad altri tipi di istanza, il che significa che è supportato un numero inferiore di dischi dati.




==== HA si abbina a BYOL

[cols="18,18,16,16,16,16"]
|===
| Esempio | Numero massimo di dischi per nodo 2+| Capacità massima del sistema con una licenza 2+| Capacità massima del sistema con più licenze 


2+|  | *Solo dischi* | *Dischi + suddivisione in livelli dei dati* | *Solo dischi* | *Dischi + suddivisione in livelli dei dati* 


| istanze c5, m5 e r5 | 18 ^1^ | 288 TiB | 368 TiB | 288 TiB | 2 PiB 


 a| 
* m5dn.24xlarge
* m6id.32xlarge

| 16 ^2^ | 256 TiB | 368 TiB | 256 TiB | 2 PiB 
|===
. 18 dischi dati è il limite per le _nuove_ distribuzioni di Cloud Volumes ONTAP.  Se si aggiorna un sistema creato con la versione 9.7 o precedente, il sistema continuerà a supportare 19 dischi.  Nei nuovi sistemi che utilizzano questi tipi di istanza è supportato un disco dati in meno grazie all'aggiunta di un disco core a partire dalla versione 9.8.
. Questo tipo di istanza ha più dischi NVMe locali rispetto ad altri tipi di istanza, il che significa che è supportato un numero inferiore di dischi dati.




== Limiti delle VM di archiviazione

Alcune configurazioni consentono di creare VM di archiviazione aggiuntive (SVM) per Cloud Volumes ONTAP.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-managing-svms-aws.html["Scopri come creare VM di archiviazione aggiuntive"^] .

[cols="40,60"]
|===
| Tipo di licenza | Limite di archiviazione VM 


| *Freemium*  a| 
24 VM di archiviazione totali ^1,2^



| *PAYGO o BYOL basato sulla capacità* ^3^  a| 
24 VM di archiviazione totali ^1,2^



| *PAYGO basato su nodi*  a| 
* 1 VM di archiviazione per la fornitura di dati
* 1 VM di archiviazione per il ripristino di emergenza




| *BYOL basato su nodi* ^4^  a| 
* 24 VM di archiviazione totali ^1,2^


|===
. Il limite può essere inferiore, a seconda del tipo di istanza EC2 utilizzata.  I limiti per istanza sono elencati nella sezione seguente.
. Queste 24 VM di archiviazione possono gestire dati o essere configurate per il disaster recovery (DR).
. Per le licenze basate sulla capacità, non sono previsti costi di licenza aggiuntivi per le VM di storage aggiuntive, ma è previsto un addebito minimo di capacità pari a 4 TiB per VM di storage.  Ad esempio, se crei due VM di archiviazione e ciascuna ha 2 TiB di capacità fornita, ti verrà addebitato un costo totale di 8 TiB.
. Per BYOL basato su nodi, è richiesta una licenza aggiuntiva per ogni VM di storage aggiuntiva per la distribuzione dei dati oltre alla prima VM di storage fornita con Cloud Volumes ONTAP per impostazione predefinita. Contatta il team del tuo account per ottenere una licenza aggiuntiva per la macchina virtuale di archiviazione.
+
Le VM di archiviazione configurate per il disaster recovery (DR) non richiedono una licenza aggiuntiva (sono gratuite), ma vengono conteggiate nel limite delle VM di archiviazione.  Ad esempio, se si dispone di 12 VM di storage per il servizio dati e 12 VM di storage configurate per il disaster recovery, si è raggiunto il limite e non è possibile creare ulteriori VM di storage.





=== Limite VM di archiviazione per tipo di istanza EC2

Quando si crea una VM di archiviazione aggiuntiva, è necessario allocare indirizzi IP privati ​​alla porta e0a.  La tabella seguente identifica il numero massimo di IP privati ​​per interfaccia, nonché il numero di indirizzi IP disponibili sulla porta e0a dopo l'implementazione Cloud Volumes ONTAP .  Il numero di indirizzi IP disponibili influisce direttamente sul numero massimo di VM di archiviazione per quella configurazione.

Le istanze elencate di seguito sono per le famiglie di istanze c5, m5 e r5.

[cols="6*"]
|===
| Configurazione | Tipo di istanza | Numero massimo di IP privati per interfaccia | IP rimanenti dopo la distribuzione ^1^ | Numero massimo di VM di archiviazione senza LIF di gestione ^2,3^ | Numero massimo di VM con storage e LIF di gestione ^2,3^ 


.9+| *Singolo nodo* | *.xlarge | 15 | 9 | 10 | 5 


| *.2xgrande | 15 | 9 | 10 | 5 


| *.4xlarge | 30 | 24 | 24 | 12 


| *.8xlarge | 30 | 24 | 24 | 12 


| *.9xlarge | 30 | 24 | 24 | 12 


| *.12xlarge | 30 | 24 | 24 | 12 


| *.16xlarge | 50 | 44 | 24 | 12 


| *.18xlarge | 50 | 44 | 24 | 12 


| *.24xlarge | 50 | 44 | 24 | 12 


.9+| *Coppia HA in singola AZ* | *.xlarge | 15 | 10 | 11 | 5 


| *.2xgrande | 15 | 10 | 11 | 5 


| *.4xlarge | 30 | 25 | 24 | 12 


| *.8xlarge | 30 | 25 | 24 | 12 


| *.9xlarge | 30 | 25 | 24 | 12 


| *.12xlarge | 30 | 25 | 24 | 12 


| *.16xlarge | 50 | 45 | 24 | 12 


| *.18xlarge | 50 | 45 | 24 | 12 


| *.24xlarge | 50 | 44 | 24 | 12 


.9+| *Coppia HA in più AZ* | *.xlarge | 15 | 12 | 13 | 13 


| *.2xgrande | 15 | 12 | 13 | 13 


| *.4xlarge | 30 | 27 | 24 | 24 


| *.8xlarge | 30 | 27 | 24 | 24 


| *.9xlarge | 30 | 27 | 24 | 24 


| *.12xlarge | 30 | 27 | 24 | 24 


| *.16xlarge | 50 | 47 | 24 | 24 


| *.18xlarge | 50 | 47 | 24 | 24 


| *.24xlarge | 50 | 44 | 24 | 12 
|===
. Questo numero indica quanti indirizzi IP privati ​​_rimanenti_ sono disponibili sulla porta e0a dopo che Cloud Volumes ONTAP è stato distribuito e configurato.  Ad esempio, un sistema *.2xlarge supporta un massimo di 15 indirizzi IP per interfaccia di rete.  Quando una coppia HA viene distribuita in una singola AZ, 5 indirizzi IP privati ​​vengono assegnati alla porta e0a.  Di conseguenza, una coppia HA che utilizza un tipo di istanza *.2xlarge ha 10 indirizzi IP privati ​​rimanenti per ulteriori VM di archiviazione.
. Il numero elencato in queste colonne include la VM di archiviazione iniziale creata da BlueXP per impostazione predefinita.  Ad esempio, se in questa colonna è elencato 24, significa che è possibile creare 23 VM di archiviazione aggiuntive per un totale di 24.
. Un LIF di gestione per la VM di archiviazione è facoltativo.  Un LIF di gestione fornisce una connessione a strumenti di gestione come SnapCenter.
+
Poiché richiede un indirizzo IP privato, limiterà il numero di VM di archiviazione aggiuntive che è possibile creare.  L'unica eccezione è una coppia HA in più AZ.  In tal caso, l'indirizzo IP per il LIF di gestione è un indirizzo IP _mobile_, quindi non viene conteggiato nel limite IP _privato_.





== Limiti di file e volumi

[cols="22,22,56"]
|===
| Archiviazione logica | Parametro | Limite 


.2+| *File* | Dimensione massima ^2^ | 128 TB 


| Massimo per volume | Dipende dalla dimensione del volume, fino a 2 miliardi 


| * Volumi FlexClone * | Profondità di clonazione gerarchica ^1^ | 499 


.3+| * Volumi FlexVol * | Massimo per nodo | 500 


| Dimensione minima | 20 MB 


| Dimensione massima ^3^ | 300 TiB 


| *Qtrees* | Massimo per FlexVol volume | 4.995 


| *Copie istantanee* | Massimo per FlexVol volume | 1.023 
|===
. La profondità di clonazione gerarchica è la profondità massima di una gerarchia annidata di volumi FlexClone che può essere creata da un singolo FlexVol volume.
. A partire da ONTAP 9.12.1P2, il limite è 128 TB.  In ONTAP 9.11.1 e nelle versioni precedenti, il limite è di 16 TB.
. La creazione FlexVol volume fino a una dimensione massima di 300 TiB è supportata utilizzando i seguenti strumenti e le seguenti versioni minime:
+
** System Manager e ONTAP CLI a partire da Cloud Volumes ONTAP 9.12.1 P2 e 9.13.0 P2
** BlueXP a partire da Cloud Volumes ONTAP 9.13.1






== Limiti di archiviazione iSCSI

[cols="3*"]
|===
| archiviazione iSCSI | Parametro | Limite 


.4+| *LUN* | Massimo per nodo | 1.024 


| Numero massimo di mappe LUN | 1.024 


| Dimensione massima | 16 TiB 


| Massimo per volume | 512 


| *igruppi* | Massimo per nodo | 256 


.2+| *Iniziatori* | Massimo per nodo | 512 


| Massimo per igroup | 128 


| *Sessioni iSCSI* | Massimo per nodo | 1.024 


.2+| *LIF* | Massimo per porta | 32 


| Massimo per set di porte | 32 


| *Portset* | Massimo per nodo | 256 
|===