---
sidebar: sidebar 
permalink: reference-configs-azure.html 
keywords: vm, explore, standard, premium, byol, capacity, maximum, virtual machine, Cloud Volumes ONTAP, supported, configurations, disks, sizes 
summary: In Azure sono supportate diverse configurazioni Cloud Volumes ONTAP . 
---
= Configurazioni supportate per Cloud Volumes ONTAP in Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
In Azure sono supportate diverse configurazioni Cloud Volumes ONTAP .



== Configurazioni supportate dalla licenza

Cloud Volumes ONTAP è disponibile in Azure come sistema a nodo singolo e come coppia di nodi ad alta disponibilità (HA) per la tolleranza agli errori e le operazioni senza interruzioni.

L'aggiornamento di un sistema a nodo singolo a una coppia HA non è supportato.  Se si desidera passare da un sistema a nodo singolo a una coppia HA, è necessario implementare un nuovo sistema e replicare i dati dal sistema esistente al nuovo sistema.

Cloud Volumes ONTAP può essere eseguito su un'istanza VM riservata o su richiesta del tuo provider cloud.  Le soluzioni che utilizzano altri tipi di istanze VM non sono supportate.

Per le specifiche delle istanze supportate, fare riferimento a https://learn.microsoft.com/en-us/azure/virtual-machines/sizes/overview["Documentazione di Microsoft Azure"^] .



=== Sistemi a nodo singolo

Quando si distribuisce Cloud Volumes ONTAP come sistema a nodo singolo in Azure, è possibile scegliere tra le seguenti configurazioni di licenza basate sulla capacità o sui nodi.

Cloud Volumes ONTAP può essere eseguito su un'istanza VM riservata o su richiesta del tuo provider cloud.  Le soluzioni che utilizzano altri tipi di istanze VM non sono supportate.

[role="tabbed-block"]
====
.Licenze basate sulla capacità
--
[cols="h,d,d,d"]
|===
|  | Freemium | Ottimizzato ^5^ | Licenza basata sulla capacità (Essentials e Professional) 


| Capacità massima del sistema (dischi + archiviazione oggetti) | 500 GB  a| 
Grazie alle licenze basate sulla capacità, ogni sistema Cloud Volumes ONTAP supporta la suddivisione in livelli per l'archiviazione di oggetti. La capacità totale a livelli può essere scalata fino al limite del bucket del provider cloud. Sebbene la licenza non imponga restrizioni di capacità, dovresti seguire le https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["Migliori pratiche FabricPool"^] per garantire prestazioni ottimali, affidabilità ed efficienza dei costi durante la configurazione e la gestione del tiering.



| Tipi di macchine virtuali supportati  a| 
* DS4_v2 ^1^
* DS5_v2 ^1^
* DS13_v2 ^1^
* DS14_v2 ^1^
* DS15_v2 ^1^
* E4s_v3 ^1^
* E8s_v3 ^1^
* E32s_v3 ^1,3^
* E48s_v3 ^1,3^
* E64is_v3 ^1,3^
* E4ds_v4
* E8ds_v4
* E32ds_v4 ^3^
* E48ds_v4 ^3^
* E80ids_v4 ^3^
* E4ds_v5
* E8ds_v5
* E20ds_v5 ^3^
* E32ds_v5 ^3^
* E48ds_v5 ^3^
* E64ds_v5 ^3^
* L8s_v3 ^2^
* L16s_v3 ^2^
* L32s_v3 ^2^
* L48s_v3 ^2^
* L64s_v3 ^2^

 a| 
* DS4_v2 ^1^
* DS13_v2 ^1^
* E4s_v3 ^1^
* E8s_v3 ^1^
* E4ds_v4 ^3^
* E8ds_v4 ^3^
* E4ds_v5
* E8ds_v5

 a| 
* DS4_v2 ^1^
* DS5_v2 ^1^
* DS13_v2 ^1^
* DS14_v2 ^1^
* DS15_v2 ^1^
* E4s_v3 ^1^
* E8s_v3 ^1^
* E32s_v3 ^1,3^
* E48s_v3 ^1,3^
* E64is_v3 ^1,3^
* E4ds_v4 ^3^
* E8ds_v4 ^3^
* E32ds_v4 ^3^
* E48ds_v4 ^3^
* E80ids_v4 ^3^
* E4ds_v5
* E8ds_v5
* E20ds_v5 ^3^
* E32ds_v5 ^3^
* E48ds_v5 ^3^
* E64ds_v5 ^3^
* L8s_v3 ^2^
* L16s_v3 ^2^
* L32s_v3 ^2^
* L48s_v3 ^2^
* L64s_v3 ^2^




| Tipi di disco supportati ^4^ 3+| Dischi gestiti Standard HDD, Dischi gestiti Standard SSD, Dischi gestiti Premium SSD e Dischi gestiti Premium SSD v2. 
|===
Note:

. ^1^ Le famiglie di macchine DS_v2 ed Es_v3 non sono più disponibili per la selezione su BlueXP quando si distribuiscono nuove istanze di Cloud Volumes ONTAP in Azure.  Queste famiglie saranno mantenute e supportate solo nei sistemi più vecchi ed esistenti.  Le nuove distribuzioni di Cloud Volumes ONTAP sono supportate in Azure solo a partire dalla versione 9.12.1.  Ti consigliamo di passare a Es_v4 o a qualsiasi altra serie compatibile con Cloud Volumes ONTAP 9.12.1 e versioni successive.  Tuttavia, le macchine delle serie DS_v2 ed Es_v3 saranno disponibili per nuove distribuzioni effettuate tramite API.
. ^2^ Questo tipo di VM include l'archiviazione NVMe locale, che Cloud Volumes ONTAP utilizza come _Flash Cache_.  Flash Cache velocizza l'accesso ai dati tramite la memorizzazione nella cache intelligente in tempo reale dei dati utente letti di recente e dei metadati NetApp .  È efficace per carichi di lavoro ad alta intensità di lettura casuale, tra cui database, posta elettronica e servizi di file. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-flash-cache.html["Saperne di più"^] .
+
La versione minima ONTAP richiesta per configurare Flash Cache su Azure è 9.13.1 GA.

. ^3^ Questi tipi di VM utilizzano un https://docs.microsoft.com/en-us/azure/virtual-machines/windows/disks-enable-ultra-ssd["Ultra SSD"^] per VNVRAM, che garantisce migliori prestazioni di scrittura.
+
Se si sceglie uno di questi tipi di VM quando si distribuisce un nuovo sistema Cloud Volumes ONTAP , non è possibile passare a un altro tipo di VM che _non_ utilizzi un Ultra SSD per VNVRAM.  Ad esempio, non è possibile passare da E8ds_v4 a E8s_v3, ma è possibile passare da E8ds_v4 a E32ds_v4 perché entrambi i tipi di VM utilizzano Ultra SSD.  Allo stesso modo, quando si distribuisce un nuovo sistema Cloud Volumes ONTAP , non è possibile modificare il tipo di VM in uno che _non_ supporta Premium SSD v2 Managed Disks.  Per saperne di più sulle configurazioni supportate per i dischi gestiti Premium SSD v2, fare riferimento a https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-ha-azure.html#ha-single-availability-zone-configuration-with-shared-managed-disks["Configurazione della zona di disponibilità singola HA con dischi gestiti condivisi"^] .

+
Al contrario, se hai distribuito Cloud Volumes ONTAP utilizzando un altro tipo di VM, non potrai passare a un tipo di VM che utilizza un Ultra SSD per VNVRAM.  Ad esempio, non è possibile passare da E8s_v3 a E8ds_v4.

. ^4^ Per informazioni sui tipi di disco supportati nelle distribuzioni a nodo singolo, fare riferimento a https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/reference-default-configs.html#azure-single-node["Azure (nodo singolo)"^] .  L'elevata velocità di scrittura è supportata con tutti i tipi di istanza quando si utilizza un sistema a nodo singolo.  È possibile abilitare l'elevata velocità di scrittura da BlueXP durante la distribuzione o in qualsiasi momento successivo. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-write-speed.html["Scopri di più sulla scelta della velocità di scrittura"^] .  Le prestazioni di scrittura migliorate sono abilitate quando si utilizzano SSD.
. ^5^ A partire dall'11 agosto 2025, la licenza Cloud Volumes ONTAP Optimized sarà deprecata e non sarà più disponibile per l'acquisto o il rinnovo nel marketplace di Azure per gli abbonamenti con pagamento in base al consumo (PAYGO). Per ulteriori informazioni, consulta  https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html#11-august-2025["Fine della disponibilità delle licenze ottimizzate"^] .


--
.Licenze basate su nodi
--
[cols="h,d,d,d,d"]
|===
|  | Esplora PAYGO | Standard PAYGO | PAYGO Premium | BYOL basato su nodi 


| Capacità massima del sistema (dischi + archiviazione oggetti) | 2 TiB ^5^ | 10 TiB | 368 TiB | 368 TiB per licenza 


| Tipi di macchine virtuali supportati  a| 
* E4s_v3 ^1^
* E4ds_v4 ^3^
* E4ds_v5

 a| 
* DS4_v2 ^1^
* DS13_v2 ^1^
* E8s_v3 ^1^
* E8ds_v4 ^3^
* E8ds_v5
* L8s_v3 ^2^

 a| 
* DS5_v2 ^1^
* DS14_v2 ^1^
* DS15_v2 ^1^
* E32s_v3 ^1,3^
* E48s_v3 ^1,3^
* E64is_v3 ^1,3^
* E32ds_v4 ^3^
* E48ds_v4 ^3^
* E80ids_v4 ^3^
* E20ds_v5 ^3^
* E32ds_v5 ^3^
* E48ds_v5 ^3^
* E64ds_v5 ^3^

 a| 
* DS4_v2 ^1^
* DS5_v2 ^1^
* DS13_v2 ^1^
* DS14_v2 ^1^
* DS15_v2 ^1^
* E4s_v3 ^1^
* E8s_v3 ^1^
* E32s_v3 ^1,3^
* E48s_v3 ^1,3^
* E64is_v3 ^1,3^
* E4ds_v4 ^3^
* E8ds_v4 ^3^
* E32ds_v4 ^3^
* E48ds_v4 ^3^
* E80ids_v4 ^3^
* E4ds_v5
* E8ds_v5
* E20ds_v5 ^3^
* E32ds_v5 ^3^
* E48ds_v5 ^3^
* E64ds_v5 ^3^
* L8s_v3 ^2^
* L16s_v3 ^2^
* L32s_v3 ^2^
* L48s_v3 ^2^
* L64s_v3 ^2^




| Tipi di disco supportati ^4^ 4+| Dischi gestiti HDD standard, dischi gestiti SSD standard e dischi gestiti SSD premium 
|===
Note:

. ^1^ Le famiglie di macchine DS_v2 ed Es_v3 non sono più disponibili per la selezione su BlueXP quando si distribuiscono nuove istanze di Cloud Volumes ONTAP in Azure.  Queste famiglie saranno mantenute e supportate solo nei sistemi più vecchi ed esistenti.  Le nuove distribuzioni di Cloud Volumes ONTAP sono supportate in Azure solo a partire dalla versione 9.12.1.  Ti consigliamo di passare a Es_v4 o a qualsiasi altra serie compatibile con Cloud Volumes ONTAP 9.12.1 e versioni successive.  Tuttavia, le macchine delle serie DS_v2 ed Es_v3 saranno disponibili per nuove distribuzioni effettuate tramite API.
. ^2^ Questo tipo di VM include l'archiviazione NVMe locale, che Cloud Volumes ONTAP utilizza come _Flash Cache_.  Flash Cache velocizza l'accesso ai dati tramite la memorizzazione nella cache intelligente in tempo reale dei dati utente letti di recente e dei metadati NetApp .  È efficace per carichi di lavoro ad alta intensità di lettura casuale, tra cui database, posta elettronica e servizi di file. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-flash-cache.html["Saperne di più"^] .
. ^3^ Questi tipi di VM utilizzano un https://docs.microsoft.com/en-us/azure/virtual-machines/windows/disks-enable-ultra-ssd["Ultra SSD"^] per VNVRAM, che garantisce migliori prestazioni di scrittura.
+
Se si sceglie uno di questi tipi di VM quando si distribuisce un nuovo sistema Cloud Volumes ONTAP , non è possibile passare a un altro tipo di VM che _non_ utilizzi un Ultra SSD per VNVRAM.  Ad esempio, non è possibile passare da E8ds_v4 a E8s_v3, ma è possibile passare da E8ds_v4 a E32ds_v4 perché entrambi i tipi di VM utilizzano Ultra SSD.

+
Al contrario, se hai distribuito Cloud Volumes ONTAP utilizzando un altro tipo di VM, non potrai passare a un tipo di VM che utilizza un Ultra SSD per VNVRAM.  Ad esempio, non è possibile passare da E8s_v3 a E8ds_v4.

. ^4^ L'elevata velocità di scrittura è supportata con tutti i tipi di istanza quando si utilizza un sistema a nodo singolo.  È possibile abilitare l'elevata velocità di scrittura da BlueXP durante la distribuzione o in qualsiasi momento successivo. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-write-speed.html["Scopri di più sulla scelta della velocità di scrittura"^] .  Le prestazioni di scrittura migliorate sono abilitate quando si utilizzano SSD.
. ^5^La suddivisione in livelli dei dati nell'archiviazione BLOB di Azure non è supportata con PAYGO Explore.


--
====


=== coppie HA

Quando si distribuisce Cloud Volumes ONTAP come coppia HA in Azure, è possibile scegliere tra le seguenti configurazioni.



==== HA si abbina al blob di pagina

È possibile utilizzare le seguenti configurazioni con le distribuzioni di blob di pagine HA Cloud Volumes ONTAP esistenti in Azure.


NOTE: I BLOB di pagine di Azure non sono supportati per nessuna nuova distribuzione.

[role="tabbed-block"]
====
.Licenze basate sulla capacità
--
[cols="h,d,d,d"]
|===
|  | Freemium | Ottimizzato ^4^ | Licenza basata sulla capacità (Essentials e Professional) 


| Capacità massima del sistema (dischi + archiviazione oggetti) | 500 GB  a| 
Grazie alle licenze basate sulla capacità, ogni sistema Cloud Volumes ONTAP supporta la suddivisione in livelli per l'archiviazione di oggetti. La capacità totale a livelli può essere scalata fino al limite del bucket del provider cloud. Sebbene la licenza non imponga restrizioni di capacità, dovresti seguire le https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["Migliori pratiche FabricPool"^] per garantire prestazioni ottimali, affidabilità ed efficienza dei costi durante la configurazione e la gestione del tiering.



| Tipi di macchine virtuali supportati  a| 
* DS4_v2
* DS5_v2 ^1^
* DS13_v2
* DS14_v2 ^1^
* DS15_v2 ^1^
* E8s_v3
* E48s_v3 ^1^
* E8ds_v4 ^3^
* E32ds_v4 ^1,3^
* E48ds_v4 ^1,3^
* E80ids_v4 ^1,2,3^
* E8ds_v5
* E20ds_v5 ^1^
* E32ds_v5 ^1^
* E48ds_v5 ^1^
* E64ds_v5 ^1^

 a| 
* DS4_v2
* DS13_v2
* E8s_v3
* E8ds_v4 ^3^
* E8ds_v5

 a| 
* DS4_v2
* DS5_v2 ^1^
* DS13_v2
* DS14_v2 ^1^
* DS15_v2 ^1^
* E8s_v3
* E48s_v3 ^1^
* E8ds_v4 ^3^
* E32ds_v4 ^1,3^
* E48ds_v4 ^1,3^
* E80ids_v4 ^1,2,3^
* E8ds_v5
* E20ds_v5 ^1^
* E32ds_v5 ^1^
* E48ds_v5 ^1^
* E64ds_v5 ^1^




| Tipi di disco supportati 3+| Blob di pagina 
|===
Note:

. ^1^ Cloud Volumes ONTAP supporta un'elevata velocità di scrittura con questi tipi di VM quando si utilizza una coppia HA.  È possibile abilitare l'elevata velocità di scrittura da BlueXP durante la distribuzione o in qualsiasi momento successivo. https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-write-speed.html["Scopri di più sulla scelta della velocità di scrittura"^] .
. ^2^ Questa macchina virtuale è consigliata solo quando è necessario il controllo della manutenzione di Azure.  Non è consigliato per altri casi d'uso a causa del prezzo più elevato.
. ^3^ Queste VM sono supportate solo nelle distribuzioni di Cloud Volumes ONTAP 9.11.1 o versioni precedenti.  Con questi tipi di VM è possibile aggiornare una distribuzione di blob di pagine esistente da Cloud Volumes ONTAP 9.11.1 a 9.12.1.  Non è possibile eseguire nuove distribuzioni di blob di pagine con Cloud Volumes ONTAP 9.12.1 o versioni successive.
. ^4^ A partire dall'11 agosto 2025, la licenza Cloud Volumes ONTAP Optimized sarà deprecata e non sarà più disponibile per l'acquisto o il rinnovo nel marketplace di Azure per gli abbonamenti con pagamento in base al consumo (PAYGO). Per ulteriori informazioni, consulta  https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html#11-august-2025["Fine della disponibilità delle licenze ottimizzate"^] .


--
.Licenze basate su nodi
--
[cols="h,d,d,d"]
|===
|  | Standard PAYGO | PAYGO Premium | BYOL basato su nodi 


| Capacità massima del sistema (dischi + archiviazione oggetti) | 10 TiB | 368 TiB | 368 TiB per licenza 


| Tipi di macchine virtuali supportati  a| 
* DS4_v2
* DS13_v2
* E8s_v3
* E8ds_v4 ^3^
* E8ds_v5

 a| 
* DS5_v2 ^1^
* DS14_v2 ^1^
* DS15_v2 ^1^
* E48s_v3 ^1^
* E32ds_v4 ^1,3^
* E48ds_v4 ^1,3^
* E80ids_v4 ^1,2,3^
* E20ds_v5 ^1^
* E32ds_v5 ^1^
* E48ds_v5 ^1^
* E64ds_v5 ^1^

 a| 
* DS4_v2
* DS5_v2 ^1^
* DS13_v2
* DS14_v2 ^1^
* DS15_v2 ^1^
* E8s_v3
* E48s_v3 ^1^
* E8ds_v4 ^3^
* E32ds_v4 ^1,3^
* E48ds_v4 ^1,3^
* E80ids_v4 ^1,2,3^
* E4ds_v5
* E8ds_v5
* E20ds_v5 ^1^
* E32ds_v5 ^1^
* E48ds_v5 ^1^
* E64ds_v5 ^1^




| Tipi di dischi dati supportati 3+| Blob di pagina 
|===
Note:

. ^1^ Cloud Volumes ONTAP supporta un'elevata velocità di scrittura con questi tipi di VM quando si utilizza una coppia HA.  È possibile abilitare l'elevata velocità di scrittura da BlueXP durante la distribuzione o in qualsiasi momento successivo. https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-write-speed.html["Scopri di più sulla scelta della velocità di scrittura"^] .
. ^2^ Questa macchina virtuale è consigliata solo quando è necessario il controllo della manutenzione di Azure.  Non è consigliato per altri casi d'uso a causa del prezzo più elevato.
. ^3^ Queste VM sono supportate solo nelle distribuzioni di Cloud Volumes ONTAP 9.11.1 o versioni precedenti.  Con questi tipi di VM è possibile aggiornare una distribuzione di blob di pagine esistente da Cloud Volumes ONTAP 9.11.1 a 9.12.1.  Non è possibile eseguire nuove distribuzioni di blob di pagine con Cloud Volumes ONTAP 9.12.1 o versioni successive.


--
====


==== Coppie HA con dischi gestiti condivisi

Quando si distribuisce Cloud Volumes ONTAP come coppia HA in Azure, è possibile scegliere tra le seguenti configurazioni.

[role="tabbed-block"]
====
.Licenze basate sulla capacità
--
[cols="h,d,d,d"]
|===
|  | Freemium | Ottimizzato ^7^ | Licenza basata sulla capacità (Essentials e Professional) 


| Capacità massima del sistema (dischi + archiviazione oggetti) | 500 GB  a| 
Grazie alle licenze basate sulla capacità, ogni sistema Cloud Volumes ONTAP supporta la suddivisione in livelli per l'archiviazione di oggetti. La capacità totale a livelli può essere scalata fino al limite del bucket del provider cloud. Sebbene la licenza non imponga restrizioni di capacità, dovresti seguire le https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["Migliori pratiche FabricPool"^] per garantire prestazioni ottimali, affidabilità ed efficienza dei costi durante la configurazione e la gestione del tiering.



| Tipi di macchine virtuali supportati  a| 
* E8ds_v4
* E32ds_v4 ^1^
* E48ds_v4 ^1^
* E80ids_v4 ^1,2^
* E8ds_v5 ^4^
* E20ds_v5 ^1,4^
* E32ds_v5 ^1,4^
* E48ds_v5 ^1,4^
* E64ds_v5 ^1,4^
* L8s_v3 ^1,3,5^
* L16s_v3 ^1,3,5^
* L32s_v3 ^1,3,5^
* L48s_v3 ^1,3,5^
* L64s_v3 ^1,3,5^

 a| 
* E8ds_v4
* E8ds_v5 ^4^

 a| 
* E8ds_v4
* E32ds_v4 ^1^
* E48ds_v4 ^1^
* E80ids_v4 ^1,2^
* E8ds_v5 ^4^
* E20ds_v5 ^1,4^
* E32ds_v5 ^1,4^
* E48ds_v5 ^1,4^
* E64ds_v5 ^1,4^
* L8s_v3 ^1,3,5^
* L16s_v3 ^1,3,5^
* L32s_v3 ^1,3,5^
* L48s_v3 ^1,3,5^
* L64s_v3 ^1,3,5^




| Tipi di disco supportati ^6^ 3+| Dischi gestiti Premium SSD o dischi gestiti Premium SSD v2. 
|===
Note:

. ^1^ Cloud Volumes ONTAP supporta un'elevata velocità di scrittura con questi tipi di VM quando si utilizza una coppia HA.  È possibile abilitare l'elevata velocità di scrittura da BlueXP durante la distribuzione o in qualsiasi momento successivo. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-write-speed.html["Scopri di più sulla scelta della velocità di scrittura"^] .
. ^2^ Questa macchina virtuale è consigliata solo quando è necessario il controllo della manutenzione di Azure.  Non è consigliato per altri casi d'uso a causa del prezzo più elevato.
. ^3^ Il supporto per più zone di disponibilità inizia dalla versione 9.13.1 ONTAP .
. ^4^ Il supporto per più zone di disponibilità inizia dalla versione ONTAP 9.14.1 RC1.
. ^5^ Questo tipo di VM include l'archiviazione NVMe locale, che Cloud Volumes ONTAP utilizza come _Flash Cache_.  Flash Cache velocizza l'accesso ai dati tramite la memorizzazione nella cache intelligente in tempo reale dei dati utente letti di recente e dei metadati NetApp .  È efficace per carichi di lavoro ad alta intensità di lettura casuale, tra cui database, posta elettronica e servizi di file. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-flash-cache.html["Saperne di più"^] .
. ^6^ Per informazioni sui dischi interni per i dati di sistema per le distribuzioni HA con zone di disponibilità singole e multiple, fare riferimento a https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/reference-default-configs.html#azure-ha-pair["Azzurro (coppia HA)"^] .
. ^7^ A partire dall'11 agosto 2025, la licenza Cloud Volumes ONTAP Optimized sarà deprecata e non sarà più disponibile per l'acquisto o il rinnovo nel marketplace di Azure per gli abbonamenti con pagamento in base al consumo (PAYGO). https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html#11-august-2025["Fine della disponibilità delle licenze ottimizzate"^] .


--
.Licenze basate su nodi
--
[cols="h,d,d,d"]
|===
|  | Standard PAYGO | PAYGO Premium | BYOL basato su nodi 


| Capacità massima del sistema (dischi + archiviazione oggetti) | 10 TiB | 368 TiB | 368 TiB per licenza 


| Tipi di macchine virtuali supportati  a| 
* E8ds_v4 ^4^
* E8ds_v5
* L8s_v3 ^4,5^

 a| 
* E32ds_v4 ^1,4^
* E48ds_v4 ^1,4^
* E80ids_v4 ^1,2,4^
* E20ds_v5 ^1^
* E32ds_v5 ^1^
* E48ds_v5 ^1^
* E64ds_v5 ^1^
* L16s_v3 ^1,4,5^
* L32s_v3 ^1,4,5^
* L48s_v3 ^1,4,5^
* L64s_v3 ^1,4,5^

 a| 
* E8ds_v4 ^4^
* E32ds_v4 ^1,4^
* E48ds_v4 ^1,4^
* E80ids_v4 ^1,2,4^
* E4ds_v5
* E8ds_v5
* E20ds_v5 ^1^
* E32ds_v5 ^1^
* E48ds_v5 ^1^
* E64ds_v5 ^1^
* L16s_v3 ^1,4,5^
* L32s_v3 ^1,4,5^
* L48s_v3 ^1,4,5^
* L64s_v3 ^1,4,5^




| Tipi di disco supportati 3+| Dischi gestiti 
|===
Note:

. ^1^ Cloud Volumes ONTAP supporta un'elevata velocità di scrittura con questi tipi di VM quando si utilizza una coppia HA.  È possibile abilitare l'elevata velocità di scrittura da BlueXP durante la distribuzione o in qualsiasi momento successivo. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-write-speed.html["Scopri di più sulla scelta della velocità di scrittura"^] .
. ^2^ Questa macchina virtuale è consigliata solo quando è necessario il controllo della manutenzione di Azure.  Non è consigliato per altri casi d'uso a causa del prezzo più elevato.
. ^3^ Questi tipi di VM sono supportati solo per coppie HA in una configurazione con zona di disponibilità singola in esecuzione su dischi gestiti condivisi.
. ^4^ Questi tipi di VM sono supportati per coppie HA in configurazioni con zona di disponibilità singola e con più zone di disponibilità in esecuzione su dischi gestiti condivisi.  Per i tipi di VM Ls_v3, il supporto per più zone di disponibilità inizia dalla versione ONTAP 9.13.1.  Per i tipi di VM Eds_v5, il supporto per più zone di disponibilità inizia dalla versione ONTAP 9.14.1 RC1.
. ^5^ Questo tipo di VM include l'archiviazione NVMe locale, che Cloud Volumes ONTAP utilizza come _Flash Cache_.  Flash Cache velocizza l'accesso ai dati tramite la memorizzazione nella cache intelligente in tempo reale dei dati utente letti di recente e dei metadati NetApp .  È efficace per carichi di lavoro ad alta intensità di lettura casuale, tra cui database, posta elettronica e servizi di file. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-flash-cache.html["Saperne di più"^] .


--
====


== Dimensioni del disco supportate

In Azure, un aggregato può contenere fino a 12 dischi, tutti dello stesso tipo e delle stesse dimensioni.



=== Sistemi a nodo singolo

I sistemi a nodo singolo utilizzano Azure Managed Disks.  Sono supportate le seguenti dimensioni di disco:

[cols="3*"]
|===
| Premium SSD | SSD standard | HDD standard 


 a| 
* 500 GB
* 1 TiB
* 2 TiB
* 4 TiB
* 8 TiB
* 16 TiB
* 32 TiB

 a| 
* 100 GB
* 500 GB
* 1 TiB
* 2 TiB
* 4 TiB
* 8 TiB
* 16 TiB
* 32 TiB

 a| 
* 100 GB
* 500 GB
* 1 TiB
* 2 TiB
* 4 TiB
* 8 TiB
* 16 TiB
* 32 TiB


|===


=== coppie HA

Le coppie HA utilizzano Azure Managed Disks.  Sono supportati i seguenti tipi e dimensioni di disco.

(I blob di pagina sono supportati con coppie HA distribuite prima della versione 9.12.1.)

*SSD Premium*

* 500 GB
* 1 TiB
* 2 TiB
* 4 TiB
* 8 TiB
* 16 TiB (solo dischi gestiti)
* 32 TiB (solo dischi gestiti)




== Regioni supportate

Per il supporto della regione di Azure, vedere https://bluexp.netapp.com/cloud-volumes-global-regions["Regioni globali di Cloud Volumes"^] .
